SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
SCREEN_TITLE = 'JumpingGame'

DISTANCE = 115
PLATS_DISTANCE = 290
MAX_WIDTH_DISTANCE = 50
DISTANCE_BETWEEN_PLATS = 45
DISTANCE_TO_TOP_PLAT= 80
START_JUMP_BARRIER_DISTANCE = 260
AFTER_JUMPING_ON_THE_FIRST_PLAT_DISTANCE = 330
MAIN_PLATFORM_DISTANCE = 118
MAP_BARRIERS_CORRECT_PLACE = 250
DISTANCE_BETWEEN_BIRDS = 200

# GRAVITY = 1
# JUMP = 15

CHAR_CENTER_X = SCREEN_WIDTH / 2
CHAR_CENTER_Y = 150

PLAT_CENTER_X = SCREEN_WIDTH / 2
PLAT_CENTER_Y = -40

JUMP_BARRIER_MOVE = 140

MONKEY_SPEED = 8
MONKEY_JUMP = 6
MONKEY_Y_LIMIT = 310
