SCREEN_WIDTH = 450
SCREEN_HEIGHT = 600
SCREEN_TITLE = 'JumpingGame'

DISTANCE = 150
PLATS_DISTANCE = 200
MAX_WIDTH_DISTANCE = 50
DISTANCE_BETWEEN_PLATS = 45

CHAR_CENTER_X = SCREEN_WIDTH / 2
CHAR_CENTER_Y = 150

PLAT_CENTER_X = SCREEN_WIDTH / 2
PLAT_CENTER_Y = 15

MONKEY_SPEED = 5
MONKEY_JUMP = 5
MONKEY_Y_LIMIT = 310
